apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: frontend-proxy-provisioner
spec:
  labels:
    node-type: frontend-proxy
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.small", "t3.medium", "t3.large"]
  limits:
    resources:
      cpu: 10
      memory: 10Gi
  providerRef:
    name: frontend-proxy
  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 3600
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: frontend-proxy
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: cilium-web-demo
  securityGroupSelector:
    karpenter.sh/discovery: cilium-web-demo
  tags:
    Name: "KarpenterWorkerNode"