---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-release
  namespace: flux-system
spec:
  dependsOn:
    - name: karpenter-provisioners
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./external-secrets
  prune: true
  wait: true