---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-s3-gw-proxy
  namespace: saleor-storefront
  labels:
    app: saleor-storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-storefront
  template:
    metadata:
      labels:
        app: saleor-storefront
    spec:
      serviceAccount: saleor-storefront-sa
      serviceAccountName: saleor-storefront-sa
      restartPolicy: Always
      containers:
      - name: nginx-s3-gateway
        image: nginxinc/nginx-s3-gateway:unprivileged-oss-20221216
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
            httpGet:
              path: /health
              port: http
        env:
          - name: ALLOW_DIRECTORY_LIST
            value: 'false'
          - name: AWS_SIGS_VERSION
            value: '4'
          - name: S3_REGION
            value: 'eu-central-1'
          - name: S3_SERVER
            value: s3.eu-central-1.amazonaws.com
          - name: S3_BUCKET_NAME
            value: 'saleor-storefront-cilium-demo'
          - name: PROVIDE_INDEX_PAGE
            value: 'true'
          - name: S3_DEBUG
            value: 'true'
          - name: S3_SERVER_PROTO
            value: 'https'
          - name: S3_SERVER_PORT
            value: '443'
          - name: S3_STYLE
            value: 'virtual'
          - name: JS_TRUSTED_CERT_PATH
            value: '/etc/ssl/certs/Amazon_Root_CA_1.pem'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                  - frontend-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: saleor-storefront-sa
  namespace: saleor-storefront
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::289512055556:role/saleor-storefront-sa
    eks.amazonaws.com/sts-regional-endpoints: "true"
  labels:
    app: saleor-storefront
---
apiVersion: v1
kind: Service
metadata:
  name: storefront-s3-gw-proxy-svc
  namespace: saleor-storefront
spec:
  selector:
    app: saleor-storefront
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: storefront-s3-gw-proxy-ingress
#   namespace: saleor-storefront
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
# spec:
#   ingressClassName: cilium
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: storefront-s3-gw-proxy-svc
#             port:
#               number: 8080