apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: saleor-storefront
  namespace: saleor-storefront
spec:
  endpointSelector:
    matchLabels:
      app: saleor-storefront
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "3000"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: "media.cilium.vodwood.codes"
      toPorts:
        - ports:
            - port: "443"
    - toFQDNs:
        - matchName: "graphql.cilium.vodwood.codes"
      toPorts:
        - ports:
            - port: "443"