apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: v0.7.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 10m
  values:
    replicaCount: 1
    leaderElect: true
    nodeSelector:
      eks.amazonaws.com/nodegroup: managed-nodegroup
    serviceAccount:
      create: true
      name: "external-secrets-sa"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::289512055556:role/external-secrets-sa
    webhook:
      replicaCount: 1
      nodeSelector:
        eks.amazonaws.com/nodegroup: managed-nodegroup
    certController:
      replicaCount: 1
      nodeSelector:
        eks.amazonaws.com/nodegroup: managed-nodegroup
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace