---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns-release
  namespace: flux-system
spec:
  dependsOn:
    - name: karpenter-provisioners
  interval: 2m
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./external-dns
  prune: true
  wait: true