---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: saleor-core
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-configuration
  interval: 2m
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core
  prune: true
  wait: true