apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-core-cert
  namespace: saleor-core
spec:
  secretName: ingress-core-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'graphql.cilium.vodwood.codes'