apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-media-assets-cert
  namespace: saleor-assets
spec:
  secretName: ingress-media-assets-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'media.cilium.vodwood.codes'