apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-static-assets-cert
  namespace: saleor-assets
spec:
  secretName: ingress-static-assets-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'static.cilium.vodwood.codes'