apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-storefront-cert
  namespace: saleor-storefront
spec:
  secretName: ingress-storefront-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'store.cilium.vodwood.codes'