apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  targetNamespace: karpenter
  interval: 15m
  chart:
    spec:
      chart: karpenter
      version: v0.20.0
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 10m
  values:
    replicas: 1
    serviceAccount:
      create: true
      name: "karpenter"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::289512055556:role/cilium-web-demo-karpenter
    settings:
      aws:
        clusterName: "cilium-web-demo"
        clusterEndpoint: "https://EC744199C3416A70221012811E2DA449.gr7.eu-central-1.eks.amazonaws.com"
        defaultInstanceProfile: "KarpenterNodeInstanceProfile-cilium-web-demo"
    logLevel: info
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace