apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saleor-postgresql
  namespace: saleor-core
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: saleor-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: saleor-postgresql
    creationPolicy: Owner
  data:
  - secretKey: saleor-postgresql-connection-string
    remoteRef:
      key: saleor-sql-connection-string
