apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saleor-redis
  namespace: saleor-core
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: saleor-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: saleor-redis
    creationPolicy: Owner
  data:
  - secretKey: saleor-redis-connection-string
    remoteRef:
      key: saleor-redis-connection-string
