apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  targetNamespace: kube-system
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: v1.12.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
      interval: 10m
  values:
    nodeSelector:
      eks.amazonaws.com/nodegroup: managed-nodegroup
    serviceAccount:
      create: true
      name: "external-dns-controller-sa"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::289512055556:role/external-dns-controller-sa