---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/external-dns