apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    email: sergeyv@duck.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-staging-account-key
    solvers:
    - selector:
        dnsZones:
          - "cilium.vodwood.codes"
      dns01:
        route53:
          region: eu-central-1
          hostedZoneID: Z02368503A60QUCYJBXIX