apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  targetNamespace: kube-system
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.10.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-system
      interval: 10m
  values:
    replicaCount: 1
    nodeSelector:
      eks.amazonaws.com/nodegroup: managed-nodegroup
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace