apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  targetNamespace: kube-system
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.10.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-system
      interval: 10m
  values:
    replicaCount: 1
    installCRDs: true
    securityContext:
      fsGroup: 1001
    serviceAccount:
      create: true
      name: cert-manager-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::289512055556:role/cert-manager-sa
    nodeSelector:
      eks.amazonaws.com/nodegroup: managed-nodegroup
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace